### ISSUE TITLE
Ranges should assume inclusive and allow for only minimum to be specified

### ISSUE THREAD

**Issue by tgharold** [ritterim/filter#15]
Right now, when searching for a PlanYear, you have to say:

PlanYear=[2015,2015]
or
PlanYear=[2015,2016]

From a usability standpoint on the API side, that is not ideal and it would be better if:
- Number ranges without inclusive/exclusive indicators should default to inclusive (i.e. 2015,2015 => [2015,2015])
- A hyphen should be supported instead of a comma, e.g. "2015-2015"
- Single numbers should automatically set the min/max to the same value, e.g. "2015"

**Comment by williambogaiv** [comment]
**Note**: this is a requested feature from internal team-members. Their use-case is when leveraging filtering using `Range<int>` for properties related to year.

**Comment by khalidabuhakmeh** [comment]
@tgharold I believe we are focusing too much on **PlanYear** and that the hyphen would not work. What if your range includes a negative value? How would you represent that with a hyphen?

```
-6--1
```

That doesn't look right to me.

**Comment by khalidabuhakmeh** [comment]
After talking to Bill, we decided to remove the hyphen separator as it is confusing for many other types. Here are a few examples where it doesn't make sense and could cause more confusion.

| hyphens | comma|
|-----------|--------------|
|A+-C-      |  A+,C-|
|B--C++   |  B-,C++ |
|-12-13 | -12, 13 |
| -100--98 | -100, -98 |

Remember, these filters are generated by code, not humans. So making them aesthetically pleasing isn't the point. The point is to be able to generate them clearly and concisely with proper intent.

**Comment by williambogaiv** [comment]
Adding to @khalidabuhakmeh's comment, we also want to avoid adding type-specific logic in order for a feature to work.

```csharp
// ...
if (typeof(T) == typeof(int))
{
    // do int-specific parsing.
}
else if (typeof(T) == typeof(DateTime))
{
    // do date-specific parsing.
}
// ...
```

There was some experimentation using em/en-dashes as a separator and while it worked, also required use of non-intuitive syntax.

**Comment by williambogaiv** [comment]
In the future, we *could* allow either full replacement of parser-expression or overload the related methods to allow custom separators. Not sure if this would be an app. setting or require instantiating `Range`-instances (versus the existing behavior of static helper methods).
