### ISSUE TITLE
Passing in array of strings does not perform substring search

### ISSUE THREAD

**Issue by tgharold** [ritterim/filter#17]
If there is a text field in the data with values like:

1. Apples
2. Oranges
3. Apples and Oranges
4. Pears
5. Kiwi
6. Pears and Peaches
7. Tomatoes
8. Apples, Oranges, Pears and Peaches

* Passing in a string array of: { "PEARS", "peach" } should return 4, 6 and 8.
* Passing in an array of { "APPLes", "kiwi" } should return 1, 3, 5, 8.

It's possible that there needs to be a way to specify entire value matching vs substring matching.  There may also need to be a way to specify case-sensitive vs case-insensitive.

My opinion is that case-insensitive and substring searches should be the default.

**Comment by khalidabuhakmeh** [comment]
This is super expensive to do because you are essentially doing a Like query, and you can much better support true **search** using other mechanisms.
