### ISSUE TITLE
Create URI construct for filter object

### ISSUE THREAD

**Issue by billbogaiv** [ritterim/filter#49]
This construct will be a single `key/value` in the querystring. It will be used in places where the client app. cannot provide a fully serialized filter-object using something like JSON.net.

Possible examples:

```
?<key>=<property1>:<value1>,<value2>;<property2>:<value1>
?<key>=<property1>:<value1>,<value2>|<property2>:<value1>
```

**Comment by khalidabuhakmeh** [comment]
You used `<` which the page treated as HTML
