### ISSUE TITLE
.NET Core model-binding is broken

### ISSUE THREAD

**Issue by billbogaiv** [ritterim/filter#77]
Ref. https://github.com/ritterim/filter/blob/1275d47b126b2439ef6fb4da938d5a4c2b00788d/src/Range.Web.Http.AspNetCore/RangeModelBinder%601.cs#L42

Currently, when a valid-result converting incoming `string` to `IRange<T>` happens, the binding context is set to the value of the `RangeResult<T>` and not its value—`IRange<T>`.

This leads to the ASP.NET Core framework reporting an error when taking `RangeResult<T>` and trying to make it `IRange<T>`.

```json
{
    "message": "Validation Failed",
    "errors": [
        {
            "message": "The value provided was not valid",
            "messages": [
                "The value provided was not valid"
            ],
            "field": "..."
        }
    ]
}
```

**Comment by kendaleiv** [comment]
Fixed via https://github.com/ritterim/filter/pull/78 in version `0.30.0`.
